### ISSUE TITLE
Local build instructions don't work

### ISSUE THREAD

**Issue by qstokkink** [flathub/org.tribler.Tribler#17]
I tried to follow the local build instructions in the `yaml`:

https://github.com/flathub/org.tribler.Tribler/blob/ab827ed11db973ee1b2198b999be91f256ae4e23/org.tribler.Tribler.yaml#L5-L7

However, this gives me the following errors:

```
$ flatpak install runtime/org.freedesktop.Sdk/x86_64/22.08
Looking for matches…
error: No remote refs found similar to ‘runtime/org.freedesktop.Sdk/x86_64/22.08’
```

I tried just ignoring the error:

```
$ flatpak-builder --force-clean build ./org.tribler.Tribler.yaml --install --user
error: org.freedesktop.Sdk/x86_64/23.08 not installed
Failed to init: Unable to find sdk org.freedesktop.Sdk version 23.08
```

And I also retried with 23.08:

```
$ flatpak install runtime/org.freedesktop.Sdk/x86_64/23.08
Looking for matches…
error: No remote refs found similar to ‘runtime/org.freedesktop.Sdk/x86_64/23.08’
```

I don't know enough about Flatpak to resolve this. Could you lend a hand?

**Comment by overflw** [comment]
Weird, when I run 
```
flatpak install runtime/org.freedesktop.Sdk/x86_64/23.08
```
I can install the runtime and also the tribler install succeeds. I can not explain your error, could it be a networking issue on your side, that somehow flatpak can not find the remote?
The comment was updated.

**Comment by qstokkink** [comment]
Thanks! I'll try again.

**Comment by qstokkink** [comment]
It turns out I forgot `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` on my testing machine. Oops.
