### ISSUE TITLE
org.freedesktop.Platform.GL.default branch 20.08 is end-of-life

### ISSUE THREAD

**Issue by damnms** [flathub/org.tribler.Tribler#7]
flatpak update
Suche nach Aktualisierungen …

Info: runtime org.freedesktop.Platform branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   org.tribler.Tribler

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.tribler.Tribler

**Comment by overflw** [comment]
Updated the runtime, ty for the hint.
